# Numpy

In [10]:
import numpy as np
np.__version__

'1.26.4'

## 넘파이 배열 이해하기
ndim(dimention, rank)   
몇차원인지 반환

In [11]:
a=np.array(0)
a, a.ndim,type(a)

(array(0), 0, numpy.ndarray)

In [3]:
a=np.array([2, 4, 6])
a, a.ndim,type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [4]:
a=[[1, 2, 3],[4, 5, 6]]
a

[[1, 2, 3], [4, 5, 6]]

In [6]:
a=np.array([[1, 2, 3],[4, 5, 6]])
a, a.ndim,type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [7]:
a=np.array([[[1, 2, 3],[4, 5, 6]],[[1, 2, 3],[4, 5, 6]]])
a, a.ndim,type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

# shape
행렬의 차원으로, 몇행 몇열인지 반환

In [8]:
a.shape?

Type:        tuple
String form: (2, 2, 3)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [9]:
a=np.array(3)
a,a.shape # 행렬이 아니기 때문

(array(3), ())

In [12]:
a=np.array([1, 3, 4, 7, 9])
a,a.shape # (5,) <- 1차원임!

(array([1, 3, 4, 7, 9]), (5,))

In [13]:
a=np.array([[1, 2, 3],[4, 5, 6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [14]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

## size
요소의 수

In [17]:
a= np.array([1, 3, 5, 7, 9])
a.size

5

In [18]:
a = np.array([[1,2,3], [4,5,6]])
a.size

6

## 넘파이 배열
* 리스트를 넘파이 배열로 생성 np.array(리스트)    
* 관련 속성: ndim 차원 반환 int, size 전체 길이 반환 int, shape 구조 반환 tuple

In [16]:
# 1차원 리스트 객체 (이터러블)
myList=[10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [19]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape}, size={myArr.size}, 길이={len(myArr)}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,), size=5, 길이=5


In [20]:
myArr

array([10, 56, 77, 23, 44])

In [21]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [22]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape}, size = {myArr2.size}, 길이={len(myArr2)}' )

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3), size = 9, 길이=3


In [23]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4],[10,20,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [24]:
# 길이가 달라 에러 리턴
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 넘파이 배열과 리스트와의 차이점
* 배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)     
* 넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등    
* 리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능


In [26]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [27]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

In [28]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [29]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지


[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


# dtype
https://numpy.org/doc/stable/reference/arrays.dtypes.html   
데이터 U유형은 각 유니코드 문자를 32비트 정수(예: 4바이트)로 저장합니다. (유니코드 스트링 dtype 인수로 지정할 자료형은 다음 표에 보인것과 같은 “dtype 접두사”로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한다.   
예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4 는 4글자 유니코드 문자열을 뜻한다    
숫자를 생략하면 운영체제에 따라 알맞은 크기를 지정한다.

In [30]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [31]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환
print(myArr_c, type(myArr_c), myArr_c.dtype)

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [32]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


# Inf와 NaN
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.   
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.    
0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [33]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


C:\Users\samsung\AppData\Local\Temp\ipykernel_340\1536815541.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\samsung\AppData\Local\Temp\ipykernel_340\1536815541.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [34]:
np.log(0)


C:\Users\samsung\AppData\Local\Temp\ipykernel_340\1608527138.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [35]:
np.exp(-np.inf)


0.0

# 기술통계

In [36]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [37]:
x.mean()

4.8076923076923075

In [38]:
np.mean(x)  # 평균


4.8076923076923075

In [39]:
np.var(x)  # 분산

115.23224852071006

In [40]:
np.std(x)  # 표준 편차

10.734628476137871

In [41]:
np.max(x)  # 최댓값

23

In [42]:
np.min(x)  # 최소값

-24

In [43]:
np.median(x)  # 중앙값

5.0

# 사분위수
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.   
각각 1사분위수, 2사분위수, 3사분위수라고 한다.   
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.   
   
때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.

In [44]:
np.percentile(x, 0)  # 최소값

-24.0

In [45]:
np.percentile(x, 25)  # 1사분위 수

0.0

In [46]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [47]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [48]:
np.percentile(x, 100)  # 최댓값

23.0

# 넘파이 함수로 배열 만들기
np.ones(n) , np.ones((x, y))   
np.zeros(n) , np.zeros((x, y))    
np.empty(n) , np.empty((x, y))    
np.aranges(start, end step)    
     
reshape(x, y) # 차원 확대    
flatten(x, y) # 차원 축소

In [49]:
# 1로 메모리 초기화, 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype) 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [50]:
print(np.ones((2,4)), np.ones((2,4)).dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [51]:
np.ones?

Signature: np.ones(shape, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and orde

In [52]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

[1 1 1 1 1 1 1 1 1 1] int32


In [53]:
# 0으로 메모리 초기화
print(np.zeros(10), np.zeros(10).dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [54]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [55]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the gi

In [56]:
# 메모리가 비어있음 -> 메모리가 초기화 되지 않는다.
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))  # 기존 메모리에 있던 값을 출력한다.(정확히 알수 없음)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[      0       1       0]
 [  32762     916       0]
 [    768       0 4456448]]


In [57]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [58]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [59]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [60]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [61]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x0000010A312A5800>
File:            c:\users\samsung\anaconda3\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end

In [62]:
np.logspace?

Signature:      
np.logspace(
    start,
    stop,
    num=50,
    endpoint=True,
    base=10.0,
    dtype=None,
    axis=0,
)
Call signature:  np.logspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function logspace at 0x0000010A312A59E0>
File:            c:\users\samsung\anaconda3\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return numbers spaced evenly on a log scale.

In linear space, the sequence starts at ``base ** start``
(`base` to the power of `start`) and ends with ``base ** stop``
(see `endpoint` below).

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.25.0
    Non-scalar 'base` is now supported

Parameters
----------
start : array_like
    ``base ** start`` is the starting value of the sequence.
stop : array_like
    ``base ** stop`` is the final value of the sequence, unless `endpoint`
    is False.  In that case, ``num + 1`` values are spaced over the
    interval in

In [63]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

# reshape 구조의 재배열
reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,   
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [64]:
arr, arr.ndim, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [65]:
arr = arr.reshape(10,5)
arr, arr.ndim, arr.shape


(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [67]:
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [68]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [69]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [70]:
print(np.arange(2,101,2).reshape(5,10))

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [71]:
np.arange(1, 31)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [72]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [73]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [74]:
# 5개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(-1, 5)
# rehsape -1은, 행무관하고 n개의 컬럼을 만든다

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [75]:
# 사이즈가 맞아야 한다.
np.arange(1, 21).reshape(-1, 7)

ValueError: cannot reshape array of size 20 into shape (7)

In [76]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [77]:
# 원본 값이 바뀜
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [78]:
a.shape = 3, -1
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [79]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

In [80]:
a.shape = -1, 2
a, a.shape

(array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 (6, 2))

In [81]:
a.shape = -1, 3
a, a.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 (4, 3))

In [82]:
# flatten
a.shape = -1
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

# 넘파이배열의 자료형 형변환
배열명2 = 배열명1.astype(자료형)   
자료형 = np.float64, np.int32

In [83]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [84]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [85]:
# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [86]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [87]:
# 정수형 => 문자열
matrix.astype('<U5')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [88]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [89]:
# 불린 -> 정수
matrix2.astype(int)

array([1, 0, 1, 1])

In [90]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [91]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [92]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

In [93]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])

# 넘파이 배열의 인덱싱
넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

# 1D array

In [94]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [95]:
a[0]

1

In [96]:
a[2]

5

In [97]:
a[4]


9

In [98]:
a[-1]


9

In [99]:
a[-3]

5

In [100]:
a[-5]

1

In [101]:
a[[0, 2, 4]]

array([1, 5, 9])

In [102]:
a


array([1, 3, 5, 7, 9])

In [103]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array( [[1,3], [4,2]] )
b

array([[1, 3],
       [4, 2]])

In [104]:
# 넘파이배열1을 넘파이배열2로 인덱싱하는 경우. 넘파이배열2는 인덱스 번호로 인식
a[b]

array([[3, 7],
       [9, 5]])

In [105]:
a[2] = 0
a

array([1, 3, 0, 7, 9])

In [106]:
a[1] += 2
a

array([1, 5, 0, 7, 9])

In [107]:
a[0] *= 6
a

array([6, 5, 0, 7, 9])

## 2D array

In [108]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [109]:
# 2차원 인덱싱할 때, 값을 하나면 넣으면 행인덱싱
a[0]

array([0, 1, 2, 3, 4])

In [110]:
a[1]

array([5, 6, 7, 8, 9])

In [111]:
a[2]

array([10, 11, 12, 13, 14])

In [112]:
a[-1]

array([10, 11, 12, 13, 14])

In [113]:
a[-2]

array([5, 6, 7, 8, 9])

In [114]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [115]:
# 값이 2개 들어가면, 행/열 인덱싱
a[0, 0]

0

In [116]:
a[0, 1]

1

In [117]:
a[0, 2]

2

In [118]:
a[1, 2]

7

In [119]:
a[2, 0]

10

In [120]:
a[-1, 2]

12

In [121]:
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
a[1] = [1, 3, 5, 7, 9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [123]:
a[-1] = 10
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [124]:
a[0] += [1, 2, 3, 4, 5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [125]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3,4)

matrix_a, matrix_b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [126]:
# 1차원에서 첫 요소와 마지막 요소
matrix_a[0], matrix_a[-1]

(0, 9)

In [127]:
# 2차원에서 1번째행 1번째열
matrix_b[0, 0]

0

In [128]:
matrix_b[0][0]

0

In [129]:
matrix_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
# 2차원 마지막행 마지막열 -> 3행 4열
matrix_b[-1,-1]

11

## 넘파이배열 슬라이싱
* 1차원   
* 넘파이배열[:end]   
* 넘파이배열[start:]   
* 넘파이배열[start:end]   
* 넘파이배열[start:end:step]    
   
* 2차원   
    
* 넘파이배열[행, 열] = [start:end:step, start2:end2:step2]   
## 1D array

In [131]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [132]:
a[:]

array([1, 3, 5, 7, 9])

In [133]:
 a[1:]


array([3, 5, 7, 9])

In [134]:
a[-1:]

array([9])

In [135]:
a[:3]

array([1, 3, 5])

In [136]:
a[:-1]

array([1, 3, 5, 7])

In [137]:
a[1:4]

array([3, 5, 7])

In [138]:
a[1:-1]

array([3, 5, 7])

In [139]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
a[::2]

array([0, 2, 4, 6, 8])

In [141]:
a[::5]


array([0, 5])

In [142]:
a[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [143]:
# 홀수
a[1::2]

array([1, 3, 5, 7, 9])

In [144]:
a[3::2]

array([3, 5, 7, 9])

In [145]:
a[:-2:2]

array([0, 2, 4, 6])

In [146]:
a[:-6:2]

array([0, 2])

In [147]:
a[2:-2:2]

array([2, 4, 6])

## 2D array

In [148]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [149]:
a[:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [150]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [151]:
a[3:]

array([], shape=(0, 5), dtype=int32)

In [152]:
a[-1:]

array([[20, 21, 22, 23, 24]])

In [153]:
a[-3:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [154]:
a[:0]

array([], shape=(0, 5), dtype=int32)

In [155]:
a[:2]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [156]:
a[:-1]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [157]:
a[:, :] # 행의 범위, 열의 범위

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [158]:
a[:, 1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [159]:
a[:, 3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [160]:
a[:, -1:]

array([[14],
       [19],
       [24]])

In [161]:
a[:, -4:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [162]:
a[:, :1]

array([[10],
       [15],
       [20]])

In [164]:
a[1:,2:3]

array([[17],
       [22]])

In [165]:
a = np.arange(10, 100).reshape(9, 10)
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [166]:
a[2:5, :]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [167]:
a[::2, ::2]

array([[10, 12, 14, 16, 18],
       [30, 32, 34, 36, 38],
       [50, 52, 54, 56, 58],
       [70, 72, 74, 76, 78],
       [90, 92, 94, 96, 98]])

In [168]:
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [169]:
a[::-1, ::-1]

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

In [170]:
matrix_c = np.arange(1, 26).reshape(5,5)
matrix_c, type(matrix_c), matrix_c.ndim

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 numpy.ndarray,
 2)

In [171]:
# 1차원 슬라이싱, 1행만 출력
matrix_c[0, :], matrix_c[0]

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [172]:
# 2차원 슬라이싱, 1번째행 2번째행 출력
matrix_c[0:2, :], matrix_c[0:2]

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]))

In [173]:
# 1번째열만 출력
matrix_c[:, 0]

array([ 1,  6, 11, 16, 21])

In [174]:
# 3,4 번째열만 출력
matrix_c[:, 2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [175]:
# 특정행의 특정열 슬라이싱
matrix_c[0:3, 0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [176]:
# 홀수번째 행만 출력
matrix_c[::2, ::]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [177]:
# 짝수번쨰행 + 홀수번째열
matrix_c[1::2, ::2]

array([[ 6,  8, 10],
       [16, 18, 20]])

In [178]:
# 리버스 인덱싱
print(matrix_c[::-1, ::]) # 행 뒤집기
print(matrix_c[::, ::-1]) # 열 뒤집기

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


# 전치행렬

In [12]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
# 2행 3열로 변환
print(matrix_d.T)

[[1 3 5]
 [2 4 6]]


In [14]:
# reshape과 transpose은 값이 다름을 유의
print(matrix_d.reshape(2,3)) 

[[1 2 3]
 [4 5 6]]


## 난수로 구성된 넘파이 배열
np.random.randint(start, end, n) : 정수 난수   
np.random.randint(start, end, (i, j))

In [15]:
np.random?

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\samsung\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\samsung\anaconda3\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to ini

In [16]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

array([3, 9, 8, 2, 5, 7, 6, 3, 2, 7])

In [17]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5))

array([[5, 1, 2, 6, 1],
       [6, 3, 8, 5, 4]])

## 섞기
np.random.shuffle(넘파이배열) 원본에 바로 적용

In [18]:
np.random.shuffle?

Docstring:
shuffle(x)

Modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a
multi-dimensional array. The order of sub-arrays is changed but
their contents remains the same.

.. note::
    New code should use the `~numpy.random.Generator.shuffle`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
x : ndarray or MutableSequence
    The array, list or mutable sequence to be shuffled.

Returns
-------
None

See Also
--------
random.Generator.shuffle: which should be used for new code.

Examples
--------
>>> arr = np.arange(10)
>>> np.random.shuffle(arr)
>>> arr
[1 7 5 2 9 4 3 6 0 8] # random

Multi-dimensional arrays are only shuffled along the first axis:

>>> arr = np.arange(9).reshape((3, 3))
>>> np.random.shuffle(arr)
>>> arr
array([[3, 4, 5], # random
       [6, 7, 8],
       [0, 1, 2]])
Type:      builtin_function_or_method

In [19]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.random.shuffle(matrix_e)
matrix_e

array([ 1,  2,  6,  7, 10,  8,  9,  3,  4,  5])

In [21]:
num= np.arange(1,46)
np.random.shuffle(num)
num[:6]

array([43, 22,  4, 18, 26, 27])

In [22]:
np.random.randint(1,46,6)

array([40, 44, 34,  2,  2, 36])

## 실수 난수
np.random.randn(n) np.random.randn(i, j)

In [23]:
np.random.randn?


Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [24]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([ 0.52726786, -0.28215349,  2.17444951,  0.47273366, -1.17662992,
       -0.52987916, -1.1557868 , -0.18330861,  0.09062783, -1.16738996])

In [25]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[ 0.3508787 , -1.40020549,  1.08249207,  0.59598824],
       [ 1.03683386,  0.75066647, -0.27119133, -0.71260042],
       [ 0.01614077, -1.29072383, -0.41574034, -1.56491606],
       [ 0.48163486, -0.53258179,  0.7955607 ,  0.20988231]])

In [26]:
matrix1.max(), matrix1.min()

(2.1744495121791614, -1.1766299205902877)

## 집계함수에서의 축
* 2차원에서의 집계합수(sum, mean)
* axis = 0, 1
* np.sum(넘파이배열, axis=0/1)
* np.mean(넘파이배열, axis=0/1)
* np.sort(넘파이배열, axis=0/1)

In [27]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[ 8, 46, 39, 20, 22],
       [41, 15, 29, 16, 19],
       [10,  3, 14, 21, 46],
       [46, 32, 33, 33, 48],
       [17, 43, 47, 20, 41]])

In [32]:
np.sum(m1, axis=0) # 열을 의미(아래로 내려가는) (x)행 합계 

array([122, 139, 162, 110, 176])

In [33]:
np.sum(m1, axis=1) # 열 (y) 합계

array([135, 120,  94, 192, 168])

In [34]:
# 1번째행의 합계는
m1[0,:]

array([ 8, 46, 39, 20, 22])

In [35]:
# 1번째행의 합계는
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

135

In [36]:
# 3번째 열의 합계는?
np.sum(m1[:, 2], axis=0)

162

## np.sort()

In [37]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[20, 32, 39],
       [43, 22, 28],
       [25, 48,  9],
       [41, 36, 35]])

In [38]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x000001482AD400E0>
File:            c:\users\samsung\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list 

In [39]:
m2

array([[20, 32, 39],
       [43, 22, 28],
       [25, 48,  9],
       [41, 36, 35]])

In [42]:
np.sort(m2) # 행안에서 열정렬 # drfault axis = -1

array([[20, 32, 39],
       [22, 28, 43],
       [ 9, 25, 48],
       [35, 36, 41]])

In [43]:
np.sort(m2, axis=0) # 행방향 오름차순(요소별로)

array([[20, 22,  9],
       [25, 32, 28],
       [41, 36, 35],
       [43, 48, 39]])

In [45]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다(+요소별 정리)

array([[41, 36, 35],
       [25, 48,  9],
       [43, 22, 28],
       [20, 32, 39]])

In [46]:
m2

array([[20, 32, 39],
       [43, 22, 28],
       [25, 48,  9],
       [41, 36, 35]])

In [48]:
np.sort(m2, axis=1) # 행정렬(열방향 오름차순)

array([[20, 32, 39],
       [22, 28, 43],
       [ 9, 25, 48],
       [35, 36, 41]])

In [49]:
m2[::-1, ::-1] 

array([[35, 36, 41],
       [ 9, 48, 25],
       [28, 22, 43],
       [39, 32, 20]])

## 인덱스 소팅
np.argsort(넘파이배열, axis=0,1)   

정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [50]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 

array([2, 1, 0], dtype=int64)

In [51]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

## 넘파이 배열 요소 추가와 삭제
* 삽입
    - np.insert(배열, 위치인덱스, 값, axis=0/1)
    - 2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력   
* 삭제    
    - np.delete(배열명, 위치인덱스, axis=0/1)

In [52]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [54]:
m3[0]

1

In [55]:
m3[-1]

10

In [56]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [57]:
np.insert(m3, len(m3), 500) 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [58]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [60]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [61]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [62]:
m4.shape, m4.shape[1], len(m4)

((3, 3), 3, 3)

In [63]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [64]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [65]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

## 배열 합치기
* np.vstack((배열1,배열2....)) : 세로 합치기   
* np.hstack((배열1,배열2....)) : 가로 합치기   
* np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

In [67]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [69]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [70]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [71]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [72]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

## boolean indexing, mask
* 조건절의 결과는 True, False로 반환
* True인 결과의 데이터 반환
* 넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~

In [73]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [74]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [75]:
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [76]:
(matrix > 10).sum()

10

In [77]:
len(matrix[matrix > 10])

10

In [78]:
np.sum(matrix > 10)

10

## Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [79]:
num = np.random.randint(1, 100, 30)
(num > 30) & (num < 70)

array([False, False, False, False,  True,  True,  True, False,  True,
       False,  True,  True, False,  True, False,  True, False,  True,
       False,  True, False, False, False, False, False,  True, False,
        True, False,  True])

In [80]:
num = np.random.randint(1,100,30)
num, num[(num > 30) & (num < 70)]

(array([95, 90, 73, 95, 97, 63, 89,  8, 39,  4, 45, 75, 37, 70, 50, 34, 18,
        79,  2, 45, 10, 60, 20, 18, 70, 23, 62,  7, 65, 76]),
 array([63, 39, 45, 37, 50, 34, 45, 60, 62, 65]))

In [83]:
num[(num > 30) & (num < 70)]

array([63, 39, 45, 37, 50, 34, 45, 60, 62, 65])

In [81]:
# ~ 은 reverse를 의미
num[~(num > 30) & (num < 70)]

array([ 8,  4, 18,  2, 10, 20, 18, 23,  7])

In [82]:
# 10보다 작거나 90보다 큰 수,
num[(num < 10) | (num > 90)]

array([95, 95, 97,  8,  4,  2,  7])

In [84]:
 num[~(num < 10) | (num > 90)]

array([95, 90, 73, 95, 97, 63, 89, 39, 45, 75, 37, 70, 50, 34, 18, 79, 45,
       10, 60, 20, 18, 70, 23, 62, 65, 76])

## fancy indexing(filtering)
넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.

* 넘파이배열1[넘파이배열2]
* 넘파이배열2 : 인덱스 역할 (only 정수형)

In [85]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([19,  3, 30, 51, 90, 24, 76, 75, 35,  5, 11, 10, 99, 61,  9, 11, 28,
         8, 99, 53, 16, 81, 97, 46, 36, 84, 89, 33, 26, 90]),
 array([19, 30, 51, 11, 16]))

## np.where()를 이용한 필터링
* np.where(조건식) : 조건식 만족하는 인덱스 반환
* np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
* 배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [86]:
np.where?


Call signature:  np.where(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function where>
Docstring:      
where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes


In [87]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [88]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4], dtype=int64),))